name: 'Upload latest release on PyPi'

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  upload_latest_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload latest release on PyPi
        uses: ./
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

