name: 'Upload latest release on PyPi'

on:
  workflow_dispatch:
  release:
    types: [published]

runs:
  using: docker
  image: Dockerfile
  env:
    TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
    TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}